
# Actions en masse sur les demandes
title=Gestion d'une pile de t\u00e2ches
plugin.description=Gestion d'une pile de t\u00e2ches
plugin.provider=Ville de Paris
daemon.purgeExpiredTasksDaemon.name=Daemon de purge des t\u00e2ches expir\u00e9es
daemon.purgeExpiredTasksDaemon.description=Ce daemon supprime les t\u00e2ches qui n'ont pas \u00e9t\u00e9 mises \u00e0 jour depuis un nombre d\u00e9termin\u00e9 de jours. Ce nombre de jours est sp\u00e9cifi\u00e9 dans la propri\u00e9t\u00e9 taskstack.task.retention.days.number.
view_task_stack.code=Code
view_task_stack.resource.id=Id Ressource
view_task_stack.resource.type=Type Ressource
view_task_stack.type=Type
view_task_stack.last_update_client_code=Code Client Derni\u00e8re Mise \u00e0 Jour
view_task_stack.date.creation=Date de Cr\u00e9ation
view_task_stack.date.last_update=Date Derni\u00e8re Mise \u00e0 jour
view_task_stack.status=Status
view_task_stack.metadata=M\u00e9tadonn\u00e9es
view_task_stack.history.show=Consulter
view_task_stack.history.title=Historique de la t\u00e2che

view_task_history.author=Auteur
view_task_history.clientcode=Code Client
view_task_history.change.type=Type de Changement
view_task_history.change.date=Date Modification

message.date.error=Une erreur est survenue durant la convertion des dates : 
message.task.recuperation.error=Une erreur est survenue durant la récupération des t\u00e2ches : 
message.task.change.recuperation.error=Une erreur est survenue durant la récupération des changements de la t\u00e2che : 